name: 'GitHub Changelog Reader'
description: 'Reads the GitHub Changelog RSS feed and creates GitHub issues for each new post'
author: 'Your Name'

inputs:
  token:
    description: 'GitHub token for creating issues'
    required: true
  label:
    description: 'Label to add to created issues'
    required: false
    default: 'changelog'
  store-location:
    description: 'File path to store the last processed entry ID'
    required: false
    default: '.github/last-changelog-guid.txt'
  issue-title-prefix:
    description: 'Prefix for issue titles'
    required: false
    default: 'GitHub Changelog: '
  feed-url:
    description: 'URL to the GitHub Changelog RSS feed'
    required: false
    default: 'https://github.blog/changelog/feed/'

outputs:
  issues-created:
    description: 'Number of new issues created'
  last-processed-guid:
    description: 'GUID of the last processed changelog entry'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'rss'
  color: 'blue'
