name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          # GitHub API token with issues:write permission
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Label to apply to created issues (default: changelog)
          label: changelog
          
          # File path to store the ID of the last processed changelog entry
          store-location: .github/last-changelog-guid.txt
          
          # Prefix for issue titles (default: "GitHub Changelog: ")
          issue-title-prefix: "GitHub Changelog: "
          
          # Optional: Number of changelog entries to process (default: 10)
          # entries-limit: 10
          
          # Optional: GitHub API URL (default: https://api.github.com)
          # github-api-url: https://api.github.com
          
          # Optional: Set to true to create issues with minimal content (default: false)
          # minimal-issues: false
          
          # Optional: Specific repository to create issues in (format: owner/repo)
          # target-repo: owner/repo

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.issues-created }}"
